### PR TITLE
Allow to skip docker_py and to modify PIP packages

### PR DESCRIPTION
**Pull request by maqdev**
- Allow to skip docker_py
- allow to modify PIP packages
- updating cache is always reported as a change

### CODE REVIEW

**Comment by atosatto** [comment]
Hi @maqdev. I really like the skip_docker_py idea.
But for which use-cases do you want to modify the installed PIP packages?

**Comment by maqdev** [comment]
Hi! Actually I don't want to install `python-pip` on target machine. In my case it depends on many other packages. So I just put `python_pip_packages: []` into into my playbook.
It seems that `pip` is only needed for `docker-py`?

**Comment by atosatto** [comment]
Hi! `pip` is needed also needed by the `Install the Python SNI support packages.` task in `main.yml` to make the `apt_key` module work.

Btw, I like your idea of making pip (and `docker-py`) optional.
Would you mind if i merge your PR in another branch (not in `master`) to resolve the conflicts and expand a little bit your idea?

In case, feel free to open an issue so that I can ask you to review my work before merging it into `master`.

**Comment by maqdev** [comment]
Sure! You're free to make whatever you want with this PR :-)

**Comment by atosatto** [comment]
Ehi @maqdev, your PR is now merged into master (see 38739a046861e1a83458a8f9150b209a1f119a35).

Thanks for your contribution!

**Pull request closed without merging**
