### PR TITLE
Major Role Refactoring and Improvements

### PR DESCRIPTION
**Pull request by atosatto**
This PR, aims to implement a number of improvements bumping this role to `v2.0.0`.

- [x] Testing: use molecule `2.5`
- [x] Testing: remove dependencies from external docker-images
- [x] Testing: tox testing against ansible `2.3` and `2.4`
- [x] Testing: increase the number of Operating Systems covered by tests
- [x] Testing: evaluate bringing back support for Ansible `2.1` and `2.2`
- [x] Improvement: install `docker-ce` instead `docker-engine` (see #31 and #37)
- [x] Bugfix: fix ssh connection reset (see #39)
- [x] Improvement: allow to override the default `docker-engine` configuration (see #29 and #30)
- [ ] Improvement: consistent prefixing of role variables (see `defaults/main.yml`)

### CODE REVIEW

**Comment by hoaile1** [comment]
Hi! I've just seen this PR by accident. I've been refactoring the role to make it up to date and cleaner. I can help with most of the things on your to-do list, but, for example, I have no experience with tox. Are you interested in collaborating with me?

**Comment by atosatto** [comment]
Ehi @hoaile1 thanks a lot for this! Feel free to open PRs against the `v2` branch. I will merge then back to this PR :)

**Comment by hoaile1** [comment]
Yay! I got motivated again.

**Comment by lnovara** [comment]
Hi! Can you please elaborate on "remove dependencies from external docker-images"? From my understanding, the point is about removing the dependency from atosatto images and use some "official" systemd-enabled image. Am I right?

**Comment by atosatto** [comment]
Ehi @lnovara, your're perfectly right.
Currently, Travis tests with Molecule depends on some external Docker images. There is no point in doing that, especially because this might cause issues with tests reproducibility.
This idea, is to implement something similar to what is done here https://github.com/PowerDNS/pdns-ansible/tree/master/molecule/common.

**Comment by holms** [comment]
When this will be merged?

**Pull request merged**
