### PR TITLE
Allow to define labels to docker swarm nodes

### PR DESCRIPTION
**Pull request by SergK**
This feature allows to define labels for swarm nodes [1]

[1]. https://docs.docker.com/engine/reference/commandline/node_update

### CODE REVIEW

**Comment by atosatto** [comment]
Ehi @SergK, thank you very much (again) for your PR.
Apparently the CI now breaks in the "Get list of labels" tasks.
Can you please check it out?

**Comment by SergK** [comment]
@atosatto sure, thank you I will check

**Comment by SergK** [comment]
That's because of docker usage as a test platform (with unpredictable hostname), e.g.

    ID                           HOSTNAME      STATUS  AVAILABILITY  MANAGER STATUS
    8g3qnyqy4frvb51o8224ebqf8    2adf83ba733c  Ready   Active        Reachable
    dejn1rkz181uz1fdwlj5n66mx *  0431e2052176  Ready   Active        Leader
    r5r1psng666t0nn2qujphgvmp    d790ff684ff8  Ready   Active 

but we are expecting `{{ inventory_hostname }}`, ok will try to find some workaround

**Comment by atosatto** [comment]
I suggest you to use the `ansible_hostname` variable instead of `inventory_hostname`.

**Comment by SergK** [comment]
@atosatto If you don't have objections I can provide tests in separate PR

**Comment by atosatto** [comment]
@SergK LGTM! Fine to me to add more tests in a separate PT. Thank you!

**Pull request merged**
