### PR TITLE
Ability to set interface name listened by docker swarm

### PR DESCRIPTION
**Pull request by Mehonoshin**
While I was testing role on vagrant machines, I've faced an issue:
Default interface was eth0, but I created additional private network, and I needed to connect swarm nodes via its interface, e.g. eth1.
So this PR adds ability to switch docker_swarm_addr to another interface address.

### CODE REVIEW

**Comment by atosatto** [comment]
Thank you @Mehonoshin for your PR.
Just a quick of questions to better understand your use-case:
why don't you just set `docker_swarm_addr: "{{ hostvars[inventory_hostname]['ansible_eth0']['ipv4']['address'] }}"`?

**Comment by Mehonoshin** [comment]
@atosatto well, I'm going to migrate to another hosting provider, and their VMs' network configuration can be slightly different.
I'd like to set VMs' _internal_ network interface name via host_vars/group_vars, so it could be more convenient to have additional `docker_swarm_interface` variable.

**Comment by atosatto** [comment]
Hi @Mehonoshin. Sorry if it took me so much time to go back to your PR. Can you please document the `docker_swarm_interface` in the README so that I can merge your contribution?

Thanks for your improvement to the role! :)

**Comment by Mehonoshin** [comment]
@atosatto I've updated README, check it out

**Comment by atosatto** [comment]
Merged by hand into master! 
Thanks @Mehonoshin for your precious contribution.

**Pull request closed without merging**
