### PR TITLE
Add become-option where it is needed

### PR DESCRIPTION
**Pull request by guenhter**
Not every ansible-user is root. So I just add the become-option to the commands which need those option. Another way would be, to set the whole play to 'become' but IMO it is better to do this only where it is really needed (on task level).

### CODE REVIEW

**Comment by atosatto** [comment]
Hey @guenhter thank you very much for this PR.

Are you using this role only to install the docker-engine or also for swarm-mode?
I think that we need to improve the role giving to the ansible_ssh user the docker group permissions (or use the become option also there) otherwise I think we would not be able to create the docker cluster.

Have you already tried it?

**Comment by guenhter** [comment]
Hey @atosatto 

actually I only use the swarm role. There I had the problem with python from the main.yml.
But I thought to add the become option to the needed tasks in the engine too.

The swarm works fine.

Do you plan to use the docker-x-module of ansible 2.2 (when the release is available) or do you stay on `shell`?

**Comment by aswadrangnekar** [comment]
checked this branch - it works well for me.

**Comment by arkadius** [comment]
Hi I've added PR #12  with task adding ansible_user to docker group. It is done quite hacky because after adding to group ssh session should be restarted. I've used some working solution from stackoverflow for it. AFAIK ansible-way solution would be to split this role to two separate roles and run them in separate plays. But IMHO it would make this extension harder to use.

**Comment by atosatto** [comment]
Hi @guenhter which module were you referring to.
I'm planning to review your PR now that Ansible 2.2.0 has been released and eventually merge your contribution.

**Comment by atosatto** [comment]
@aswadrangnekar were you having some issues running this role without the become option?

**Comment by guenhter** [comment]
@atosatto
I just ment the docker modules in general, because currently the shell-module is heavily used.

**Comment by atosatto** [comment]
@guenhter yep. But unfortunately I don't think is possible to use the Docker module to fetch the info from the docker daemon or control docker-swarm. This is why I used the shell module, even if is not the best thing to do. Did you found any issue with it?

PS: Can you give me write access to your PR (https://github.com/blog/2247-improving-collaboration-with-forks). I'd like to make some minor changes before merging.

**Comment by guenhter** [comment]
The "Allow edits from maintainers" is already activated on this PR. I guess editing should work for you.

No, I didn't have any issues with it. Just a fan of using modules as much as possible thats all.

**Comment by guenhter** [comment]
Not really good

**Pull request closed without merging**
